### ISSUE TITLE
Can't jump to lyrics when clicked.

### ISSUE THREAD

**Issue by kindercha360** [Astromations/Hazy#6]
Hello, I found your theme on spicetify marketplace and it's awesome! But I have an issue about the lyrics. Can you make the skip lyrics feature, like tap on the specific lyrics and jump onto those lyrics? Thank you very much!

p.s and for lyrics cinema mode, can you make it with colored background and not transparent one? or there is a way to make it with colored background? Thank you very much!

**Comment by Astromations** [comment]
Which window are you talking about. If you are referring to the lyrics in the sidebar, its not possible to skip to lyrics on click. Otherwise, for fullscreen lyrics and synced lyrics-plus, it's working fine on my end. 


As for the cinema mode. the point of the theme is to be transparent through and through. If you insist on a colored background, the "Beautiful Lyrics" extension overrides the transparency. 

![image](https://github.com/Astromations/Hazy/assets/80211195/491e21ce-3e29-4e88-819d-6359cbc092ed)
