### ISSUE TITLE
Cant customize background

### ISSUE THREAD

**Issue by IloveMyHusbandVoilet** [Astromations/Hazy#69]
I wanted to put my beloved amazing breathtaking Husband as my background on Spotify but it doesn't work it doesn't let me customize the background image and I have no idea why 

help

**Comment by Astromations** [comment]
I see you love your husband very much, and it is truly devastating that you've been unable to make him your background. Might I ask if you are using a link or a locally saved image. In the latter case, I recommend uploading the local image to Imgur or some other image hosting platform (I'm sure they'll love to host a picture of your amazing husband), at which point, you can copy the link and use that in the customization window. 

However, if the former is true, and you are in fact already using a link, you might want to play a song to make sure that all the javascript refreshes. If that doesn't work, there's a bigger issue with the theme that I would have to remedy in order to allow you to have your beloved husband as your spotify background.

**Comment by Astromations** [comment]
Hi. Just wanted to check in. Have you been able to find a way to have your magnificent husband as your background yet?

**Comment by H5uk3** [comment]
Nope still not working, ive tried too

**Comment by Astromations** [comment]
I am having trouble replicating this issue. As of now, these are the latest Spotify and Spicetify versions. 
![image](https://github.com/Astromations/Hazy/assets/80211195/88c55c59-b003-49ff-bf41-93c4892dc551)
You can download the latest Spotify windows version [here](https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.35.663.gb699649e-6898.exe) and you can run ```spicetify upgrade``` to get on the latest Spicetify. Try that and see if the issue persists.
